# Config file .travis.yml
sudo: false

addons:
  apt:
    packages:
        - expect-dev
        - python-lxml

language: python

python:
  - "2.7"
  
env:
    - VERSION="8.0" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - pip install flake8
  - git clone https://github.com/CompassionCH/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b r2
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

script:
  - test_flake8
  - travis/travis_header.sh

notifications:
  email: false
