# Config file .travis.yml
language: python

python:
  - "2.7"

install:
  - pip install flake8
  - git clone https://github.com/CompassionCH/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b r2
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

script:
  - test_flake8
  - travis/travis_header.sh
  - travis_run_tests

notifications:
  email: false
